
			<div id="basic">
				<h1>Brons</h1>
					<p><span class="excluded glyphicon glyphicon-remove"></span> livestream</p>

					<p><span class="excluded glyphicon glyphicon-remove"></span> Workshop</p>
				
					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 2</p>
				
					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 3</p>

					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 4</p>
				{{ form("package/package1") }}
				{{ submit_button("id":"brons", "name": "pakket1", "class": "btn btn-primary bestelbtn", "onclick":"packages();") }}
				{{ end_form() }}
			</div>	
