
<div id="premium">
				<h1>Goud</h1>
					<p><span class="included glyphicon glyphicon-ok"></span> livestream</p>

					<p><span class="included glyphicon glyphicon-ok"></span> Worskhop</p>
				
					<p><span class="included glyphicon glyphicon-ok"></span> workshop deel 2</p>
				
					<p><span class="included glyphicon glyphicon-ok"></span> workshop deel 3</p>

					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 4</p>
				 	{{ form("package/package3") }}
				{{ submit_button("name": "pakket3", "class": "btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha") }}
				{{ end_form() }}
			</div>
