
<div id="plus">
				<h1>Zilver</h1>
					<p><span class="included glyphicon glyphicon-ok"></span> livestream</p>

					<p><span class="included glyphicon glyphicon-ok"></span> Worskhop</p>
				
					<p><span class="included glyphicon glyphicon-ok"></span> workshop deel 2</p>
				
					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 3</p>

					<p><span class="excluded glyphicon glyphicon-remove"></span> workshop deel 4</p>
					{{ form("package/package2") }}
				{{ submit_button("name": "pakket2", "class": "btn btn-primary bestelbtn") }}
				{{ end_form() }}
			</div>
