<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

</header>
<div class="container">
<a href="/kphalcon/admin/changelvl/"><h4 class="glyphicon glyphicon-pencil">Verander gebruiker Pakket</h4></a></br>
<a href="/kphalcon/mediaplayer/videoactions/"><h4 class="glyphicon glyphicon-pencil">Verwijder Masterclasses</h4></a>
</br>
<a href="/kphalcon/mediaplayer/bronsvideo/"><h4 class="glyphicon glyphicon-pencil">Voeg een Masterclass toe: Brons</h4></a>
</br>
<a href="/kphalcon/mediaplayer/zilvervideo/"><h4 class="glyphicon glyphicon-pencil">Voeg een Masterclass toe: Zilver</h4></a>
</br>
<a href="/kphalcon/mediaplayer/goldvideo/"><h4 class="glyphicon glyphicon-pencil">Voeg een Masterclass toe: Goud</h4></a>
</div>

