<h1>{{auth['firstname']}} {{auth['lastname']}}</h1>
<h1>{{auth['email']}}</h1>
<a href="/kphalcon/admin/changelvl/"><h1 class="glyphicon glyphicon-pencil">change_user_lvl</h1></a></br>
<a href="/kphalcon/mediaplayer/videoactions/"><h1 class="glyphicon glyphicon-pencil">delete_video's</h1></a>
</br>
<a href="/kphalcon/mediaplayer/bronsvideo/"><h1 class="glyphicon glyphicon-pencil">Voeg_brons_video_toe</h1></a>
</br>
<a href="/kphalcon/mediaplayer/zilvervideo/"><h1 class="glyphicon glyphicon-pencil">Voeg_zilver_video_toe</h1></a>
</br>
<a href="/kphalcon/mediaplayer/goldvideo/"><h1 class="glyphicon glyphicon-pencil">Voeg_gold_video_toe</h1></a>