<?php 
$show = $this->session->get('mediaid');
$media = mediabrons::findFirstBymedia_id($show['id']);
?>
<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

  
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">NEVER UNDERESTIMATE THE POWER OF THE YOUNG.</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

    </header>
    <div class="container">
        {% if auth %}
    <h1>Hello! https://www.sitepoint.com/sending-confirmation-emails-phalcon-swift/
    </h1>
    <h1>welcome you great person!!</h1>
    {% endif %}

<h1>Nieuwste video's</h1>
                    <div id="cards" class="cards">
                        {% for mediabrons in mediabrons %}
                            <div class="card card--alpha" style="height: 483px;">
                                <?php
                                        $mediaid = $mediabrons->media_id;
                                    ?>
                                    <a href="mediaplayer/playbrons?id=<?php echo $mediaid;?>">  
                                    <img src="/kphalcon/public/img/thumbnail/{{ mediabrons.thumbnail }}.png" height="200" width="300"></img>
                                    </a>  
                                <div class="card__content">
                                    <h5 class="card__title">{{mediabrons.title}}</h5>
                                    <p class="card__intro" data-ellipsis="" style="word-wrap: break-word;">{{mediabrons.description}}</p>
                                    <ul class="list-inline">
                                        <li><a data-show-article="" class="btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha" href="playbrons?id=<?php echo $mediaid;?>">lees meer</a></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                    </div>
                    

                    
                    <div id="cards" class="cards">
                        {% for mediazilver in mediazilver %}
                            <div class="card card--alpha" style="height: 483px;">
                                <?php
                                        $mediaid = $mediazilver->media_id;
                                    ?>
                                    <a href="mediaplayer/playzilver?id=<?php echo $mediaid;?>">  
                                    <img src="/kphalcon/public/img/thumbnail/{{ mediabrons.thumbnail }}.png" height="200" width="300"></img>
                                    </a>  
                                <div class="card__content">
                                    <h5 class="card__title">{{mediazilver.title}}</h5>
                                    <p class="card__intro" data-ellipsis="" style="word-wrap: break-word;">{{mediazilver.description}}</p>
                                    <ul class="list-inline">
                                        <li><a data-show-article="" class="btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha" href="playbrons?id=<?php echo $mediaid;?>">lees meer</a></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                    </div>
                      
                    
                    
                    <div id="cards" class="cards">
                        {% for mediagold in mediagold %}
                            <div class="card card--alpha" style="height: 483px;">
                                <?php
                                        $mediaid = $mediagold->media_id;
                                    ?>
                                    <a href="mediaplayer/playgold?id=<?php echo $mediaid;?>">  
                                    <img src="/kphalcon/public/img/thumbnail/{{ mediabrons.thumbnail }}.png" height="200" width="300"></img>
                                    </a>  
                                <div class="card__content">
                                    <h5 class="card__title">{{mediagold.title}}</h5>
                                    <p class="card__intro" data-ellipsis="" style="word-wrap: break-word;">{{mediagold.description}}</p>
                                    <ul class="list-inline">
                                        <li><a data-show-article="" class="btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha" href="/artikel/bigid-zoekt-een-grafisch-vormgever/">lees meer</a></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                    </div>

