   <header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

  
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">NEVER UNDERESTIMATE THE POWER OF THE YOUNG.</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

    </header>
    
{% if auth %}
	<h1>Hello! https://www.sitepoint.com/sending-confirmation-emails-phalcon-swift/
	</h1>
	<h1>welcome you great person!!</h1>
	{% else %}
<h1>Nieuwste video's</h1>
<div class="col-md-4">

{% for mediabrons in mediabrons %}
<li>	
<iframe src="{{ mediabrons.videos }}"></iframe>
</br>
<h1>{{mediabrons.title}}</h1>
</br>
{{mediabrons.description}}
</li>	
{% endfor %} 
</div>

<div class="col-md-4">
{% for mediazilver in mediazilver %}
<li>	
<iframe src="{{ mediazilver.videos }}"></iframe>
</br>
<h1>{{mediazilver.title}}</h1>
 </br>
{{mediazilver.description}}
</li>	
{% endfor %} 
</div>

<div class="col-md-4">
{% for mediagold in mediagold %}
<li>	
<iframe src="{{ mediagold.videos }}"></iframe>
</br>
<h1>{{mediagold.title}}</h1>
 </br>
{{mediagold.description}}
</li>	
{% endfor %} 


{% endif %}
