<?php 
$show = $this->session->get('mediaid');
$media = mediabrons::findFirstBymedia_id($show['id']);
?>


<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

  
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">NEVER UNDERESTIMATE THE POWER OF THE YOUNG.</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

    </header>
    <div class="container">
        {% if auth %}
    <h1>Hello! https://www.sitepoint.com/sending-confirmation-emails-phalcon-swift/
    </h1>
    <h1>welcome you great person!!</h1>
    {% endif %}
<h1>Nieuwste video's</h1>
<div class="col-md-4">
{% for mediabrons in mediabrons %}
<?php
$mediaid = $mediabrons->media_id;
?>
<a href="mediaplayer/playbrons?id=<?php echo $mediaid;?>">
<img src="public/img/thumbnail/{{ mediabrons.thumbnail }}.png" height="200" width="300"></img>
</a>
</br>
<h1>{{mediabrons.title}}</h1>
</br>
{{mediabrons.description}}
{{mediabrons.programma}}
</br>   
{% endfor %} 
</div>

<div class="col-md-4">
{% for mediazilver in mediazilver %}
<?php
$mediaid = $mediazilver->media_id;
?>
<a href="mediaplayer/playzilver?id=<?php echo $mediaid;?>">
<img src="public/img/thumbnail/{{ mediazilver.thumbnail }}.png" height="200" width="300"></img>
</a>
</br>
<h1>{{mediazilver.title}}</h1>
 </br>
{{mediazilver.description}} 
{{mediazilver.programma}}
</br>
{% endfor %} 
</div>

<div class="col-md-4">
{% for mediagold in mediagold %}
<?php
$mediaid = $mediagold->media_id;
?>
<a href="mediaplayer/playgold?id=<?php echo $mediaid;?>">   
<img src="public/img/thumbnail/{{ mediagold.thumbnail }}.png" height="200" width="300"></img>
</a>
</br>
<h1>{{mediagold.title}}</h1>
</br>
{{mediagold.description}}
{{mediagold.programma}} 
</br>
{% endfor %} 


