<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_header.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase"> CHANGE IS THE END RESULT OF ALL TRUE LEARNING</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

    </header>

    <section class="section section--alpha">
        <div class="container">
        
        
        
        
                    <div id="cards" class="cards">
                            <div class="card card--alpha" style="height: 483px;">
                                {% for mediabrons in mediabrons %}
                                    <?php
                                        $mediaid = $mediabrons->media_id;
                                    ?>  
                                    <li>
                                        <a href="playbrons?id=<?php echo $mediaid;?>">  
                                        <img src="/kphalcon/public/img/thumbnail/{{ mediabrons.thumbnail }}.png" height="200" width="300"></img>
                                    </a>
                                    </br>
                                    <h1>{{mediabrons.title}}</h1>
                                     </br>
                                        {{mediabrons.description}}
                                    </li>   
                                {% endfor %} 
                            </div>
                            <div class="card card--alpha" style="height: 483px;">
                                {% for mediazilver in mediazilver %}
                                    <?php
                                        $mediaid = $mediazilver->media_id;
                                    ?>
                                    <li>
                                        <a href="playzilver?id=<?php echo $mediaid;?>">     
                                        <img src="/kphalcon/public/img/thumbnail/{{ mediazilver.thumbnail }}.png" height="200" width="300">                             </img>
                                    </a>
                                    </br>
                                <h1>{{mediazilver.title}}</h1>
                                    </br>
                                        {{mediazilver.description}}
                                    </li>   
                                {% endfor %} 
                                </div>
                                <div class="card card--alpha" style="height: 483px;">
                                    {% for mediagold in mediagold %}
                                    <?php
                                        $mediaid = $mediagold->media_id;
                                    ?>
                                    <li>
                                        <a href="playgold?id=<?php echo $mediaid;?>">   
                                            <img src="/kphalcon/public/img/thumbnail/{{ mediagold.thumbnail }}.png" height="200" width="300"></img>
                                        </a>
                                        </br>
                                            <h1>{{mediagold.title}}</h1>
                                        </br>
                                            {{mediagold.description}}
                                    </li>   
                                    {% endfor %} 
                                </div>
                    </div>
                    
                    
                    
                </div>
            </section>