<?php
$show = $this->session->get('mediaid');
$media = mediabrons::findFirstBymedia_id($show['id']);
?>
<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

</header>
<div class="container">
{% if auth['lvl'] > 3 %}	
<iframe src="{{ media.videos }}" width="854" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
{% else %}
<div class="container container-beta">
<div style="width:100%; height:100%;">
<div style="position:absolute; top:30px;">
<img style="position:relative" src="../img/thumbnail/{{ media.thumbnail }}.png" height="600" width="900"></img>
<h1 style="left:0; width:100%; top:30px; position:absolute; color:red; text-align:center">Sorry, deze video is alleen</br> te bekijken door pakketjesgebruikers</h1>
</div>
</div>
</div>
{% endif %}
</br>
<h1>{{media.title}}</h1>
</br>
{{media.description}}	
</div>
