<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_stage.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">NEVER UNDERESTIMATE THE POWER OF THE YOUNG.</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

            
            <div class="header__sub-text-container">

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/top-line-header-sub-text.svg">

                <h4 class="header__sub-text text-transform-uppercase">Young creatives</h4>

                <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/svg/bottom-line-header-sub-text.svg">

            </div>

        </div>

    </header>
<div class="container">
    <h2>Credits</h2>
    <p>Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen. Met deze credits kunt de masterclasses aanschaffen.</p>
</div>
<div class="container">
    <div class="alignbody">
		<div class="alignpackage credits">
			{{ partial("credit/package1")}} 
			{{ content()}}
        </div>
        <div class="alignpackage credits">
            {{ partial("credit/package2")}}
        </div> 
        <div class="alignpackage credits"> 
            {{ partial("credit/package3")}} 
            {{ content()}}
        </div>
        <div class="alignpackage credits"> 
            {{ partial("credit/package4")}} 
            {{ content()}}
        </div> 
        <div class="alignpackage credits"> 
            {{ partial("credit/package5")}} 
            {{ content()}}
        </div>       
		
			
		

	</div>
	
</div>

