<div class="row"></div>

		


<div class="container">
<h1>Contact page</h1>

<div id="contactlist" class="col-md-6">

<h2>Kweekvijver Noord:  </h2><br>
Telefoon: 06-53368535 <br>
E-mail: <a href="mailto:info@kweekvijvernoord.nl">info@kweekvijvernoord.nl</a> <br>
Website: <a href="http://www.kweekvijvernoord.nl">www.kweekijvernoord.nl</a><br>
Openingstijden: Maandag - Vrijdag 9:00 - 17:00<br>
Adres: Zuiderplein 4 <br>
8911 AJ Leeuwarden  <br> <br>
Sociale Media: <br>
<a href="https://www.facebook.com/KweekvijverNoord.nl">Twitter</a> -- 
<a href="https://twitter.com/Kweekvijvern">Facebook</a> -- 
<a href="https://plus.google.com/+KweekvijverNoord">Google+</a> -- 
<a href="https://www.youtube.com/channel/UCWV6W0eT3Z4LSiNfedxDpCQ">Youtube</a><br>
</div>



<div id="neushoornlocation" class="col-md-6">
<h4>Waar worden de workshops gehouden?</h4>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2389.977692089661!2d5.787979415558343!3d53.20031627994871!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c8fe820d6b9567%3A0x1496149010f309cc!2sNeushoorn!5e0!3m2!1snl!2snl!4v1488807333066" width="300" height="250" frameborder="5" style="border:5px" allowfullscreen></iframe>
</div>


</div>






