<!-- <div class="container col-md-12"> -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <!-- Collect the nav links, forms, and other content for toggling -->
   <!--  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
      <ul class="nav navbar-nav">
        <a class="navbar-brand" href="/kphalcon/"><div class="logo-kweekvijver"><img src="/kphalcon/public/img/kweek-logo-1.png" ></img></div></a>
        <li>
        <a href="/kphalcon/package">Pakketten</a>
      </li>
        <li class="test1"><a href="/kphalcon/contact/">Contact</a></li>
        <li><a id="aboutus" href="/kphalcon/aboutus/">Over ons</a></li>
        <li><a id="faq" href="/kphalcon/faq/">FAQ</a></li>
        <!--Begin van de authenticatie. bij de sessie zie je dat je het niveau van de authenticatie aan kan passen. (is eigenlijk gewoon een if loop maar dan in volt)  -->
        {% if auth %}
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">video's<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a id="mediaplayer" href="/kphalcon/mediaplayer/">Mediaspeler</a></li>
        </ul>
      </li>
        {% endif %}
        </ul>
        {% if auth %}
         <ul class=" nav navbar-nav navbar-right">
           <!--Hier zie je hoe simpel het is om met volt verschillende objecten uit het user model te halen. de user model haalt de informatie weer uit de database.-->
         <li><a>Ingelogd als {{auth['firstname']}} {{auth['lastname']}}</a></li>
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Opties<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/kphalcon/session/profile">Profiel</a></li>
                  <li><a href="#">Instellingen</a></li>
                  <li><a href="#">Berichten</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Sessie</li>
                  {% if auth['lvl'] == 6 %}
                  <li><a href="/kphalcon/admin">Admin options</a></li>
                  {% endif%}
                  <li><a id="log-out" href="/kphalcon/session/logout"><span class="glyphicon glyphicon-log-out"></span> Log-out</a></li>
                </ul>
              </li>
      {% else %}
       <ul class="nav navbar-nav navbar-right">
        <li><a id="register" href="/kphalcon/session/register"><span class="glyphicon glyphicon-user"></span> Registreren</a></li>
        <li><a id="log-in" href="/kphalcon/session/"><span class="glyphicon glyphicon-log-in"></span> Log-in</a></li>
      </ul>
      {% endif%}
    </div><!-- /.navbar-collapse -->
    </div>
</nav>
<!-- </div> -->






